<?php
/**
 * AbstractApplicationParameterValueTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Agave\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Agave Platform Science API
 *
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Agave\Client;

/**
 * AbstractApplicationParameterValueTest Class Doc Comment
 *
 * @category    Class
 * @description AbstractApplicationParameterValue
 * @package     Agave\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AbstractApplicationParameterValueTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AbstractApplicationParameterValue"
     */
    public function testAbstractApplicationParameterValue()
    {
    }

    /**
     * Test attribute "default_value"
     */
    public function testPropertyDefaultValue()
    {
    }

    /**
     * Test attribute "enum_values"
     */
    public function testPropertyEnumValues()
    {
    }

    /**
     * Test attribute "enquote"
     */
    public function testPropertyEnquote()
    {
    }

    /**
     * Test attribute "order"
     */
    public function testPropertyOrder()
    {
    }

    /**
     * Test attribute "required"
     */
    public function testPropertyRequired()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "validator"
     */
    public function testPropertyValidator()
    {
    }

    /**
     * Test attribute "visible"
     */
    public function testPropertyVisible()
    {
    }
}
