<?php
/**
 * JobTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Agave\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Agave Platform Science API
 *
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Agave\Client;

/**
 * JobTest Class Doc Comment
 *
 * @category    Class
 * @description Job
 * @package     Agave\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class JobTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Job"
     */
    public function testJob()
    {
    }

    /**
     * Test attribute "app_id"
     */
    public function testPropertyAppId()
    {
    }

    /**
     * Test attribute "archive"
     */
    public function testPropertyArchive()
    {
    }

    /**
     * Test attribute "archive_path"
     */
    public function testPropertyArchivePath()
    {
    }

    /**
     * Test attribute "archive_system"
     */
    public function testPropertyArchiveSystem()
    {
    }

    /**
     * Test attribute "batch_queue"
     */
    public function testPropertyBatchQueue()
    {
    }

    /**
     * Test attribute "end_time"
     */
    public function testPropertyEndTime()
    {
    }

    /**
     * Test attribute "execution_system"
     */
    public function testPropertyExecutionSystem()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "inputs"
     */
    public function testPropertyInputs()
    {
    }

    /**
     * Test attribute "local_id"
     */
    public function testPropertyLocalId()
    {
    }

    /**
     * Test attribute "memory_per_node"
     */
    public function testPropertyMemoryPerNode()
    {
    }

    /**
     * Test attribute "message"
     */
    public function testPropertyMessage()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "node_count"
     */
    public function testPropertyNodeCount()
    {
    }

    /**
     * Test attribute "notifications"
     */
    public function testPropertyNotifications()
    {
    }

    /**
     * Test attribute "output_path"
     */
    public function testPropertyOutputPath()
    {
    }

    /**
     * Test attribute "owner"
     */
    public function testPropertyOwner()
    {
    }

    /**
     * Test attribute "parameters"
     */
    public function testPropertyParameters()
    {
    }

    /**
     * Test attribute "processors_per_node"
     */
    public function testPropertyProcessorsPerNode()
    {
    }

    /**
     * Test attribute "max_run_time"
     */
    public function testPropertyMaxRunTime()
    {
    }

    /**
     * Test attribute "retries"
     */
    public function testPropertyRetries()
    {
    }

    /**
     * Test attribute "start_time"
     */
    public function testPropertyStartTime()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "submit_time"
     */
    public function testPropertySubmitTime()
    {
    }

    /**
     * Test attribute "work_path"
     */
    public function testPropertyWorkPath()
    {
    }
}
