<?php
/**
 * JobsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Agave\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Agave Platform Science API
 *
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Agave\Client;

use \Agave\Client\Configuration;
use \Agave\Client\ApiException;
use \Agave\Client\ObjectSerializer;

/**
 * JobsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Agave\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class JobsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addJobPermission
     *
     * .
     *
     */
    public function testAddJobPermission()
    {
    }

    /**
     * Test case for clearJobPermissions
     *
     * .
     *
     */
    public function testClearJobPermissions()
    {
    }

    /**
     * Test case for deleteJob
     *
     * .
     *
     */
    public function testDeleteJob()
    {
    }

    /**
     * Test case for deleteJobPermission
     *
     * .
     *
     */
    public function testDeleteJobPermission()
    {
    }

    /**
     * Test case for downloadJobOutput
     *
     * .
     *
     */
    public function testDownloadJobOutput()
    {
    }

    /**
     * Test case for getJobDetails
     *
     * .
     *
     */
    public function testGetJobDetails()
    {
    }

    /**
     * Test case for getJobHistory
     *
     * .
     *
     */
    public function testGetJobHistory()
    {
    }

    /**
     * Test case for getJobPermission
     *
     * .
     *
     */
    public function testGetJobPermission()
    {
    }

    /**
     * Test case for getJobStatus
     *
     * .
     *
     */
    public function testGetJobStatus()
    {
    }

    /**
     * Test case for listJobOutputs
     *
     * .
     *
     */
    public function testListJobOutputs()
    {
    }

    /**
     * Test case for listJobPermissions
     *
     * .
     *
     */
    public function testListJobPermissions()
    {
    }

    /**
     * Test case for listJobs
     *
     * .
     *
     */
    public function testListJobs()
    {
    }

    /**
     * Test case for resubmitJob
     *
     * .
     *
     */
    public function testResubmitJob()
    {
    }

    /**
     * Test case for submitJob
     *
     * .
     *
     */
    public function testSubmitJob()
    {
    }

    /**
     * Test case for updateJobPermission
     *
     * .
     *
     */
    public function testUpdateJobPermission()
    {
    }
}
