<?php
/**
 * SystemsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Agave\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Agave Platform Science API
 *
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Agave\Client;

use \Agave\Client\Configuration;
use \Agave\Client\ApiException;
use \Agave\Client\ObjectSerializer;

/**
 * SystemsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Agave\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SystemsApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addExecutionSystem
     *
     * .
     *
     */
    public function testAddExecutionSystem()
    {
    }

    /**
     * Test case for addStorageSystem
     *
     * .
     *
     */
    public function testAddStorageSystem()
    {
    }

    /**
     * Test case for addSystemCredential
     *
     * .
     *
     */
    public function testAddSystemCredential()
    {
    }

    /**
     * Test case for addSystemRole
     *
     * .
     *
     */
    public function testAddSystemRole()
    {
    }

    /**
     * Test case for clearSystemAuthCredentials
     *
     * .
     *
     */
    public function testClearSystemAuthCredentials()
    {
    }

    /**
     * Test case for clearSystemAuthCredentialsForInternalUser
     *
     * .
     *
     */
    public function testClearSystemAuthCredentialsForInternalUser()
    {
    }

    /**
     * Test case for clearSystemRoles
     *
     * .
     *
     */
    public function testClearSystemRoles()
    {
    }

    /**
     * Test case for deleteSystem
     *
     * .
     *
     */
    public function testDeleteSystem()
    {
    }

    /**
     * Test case for deleteSystemAuthCredentialForInternalUser
     *
     * .
     *
     */
    public function testDeleteSystemAuthCredentialForInternalUser()
    {
    }

    /**
     * Test case for deleteSystemRole
     *
     * .
     *
     */
    public function testDeleteSystemRole()
    {
    }

    /**
     * Test case for getSystemCredential
     *
     * .
     *
     */
    public function testGetSystemCredential()
    {
    }

    /**
     * Test case for getSystemDetails
     *
     * .
     *
     */
    public function testGetSystemDetails()
    {
    }

    /**
     * Test case for getSystemRole
     *
     * .
     *
     */
    public function testGetSystemRole()
    {
    }

    /**
     * Test case for invokeSystemAction
     *
     * .
     *
     */
    public function testInvokeSystemAction()
    {
    }

    /**
     * Test case for listCredentialsForInternalUser
     *
     * .
     *
     */
    public function testListCredentialsForInternalUser()
    {
    }

    /**
     * Test case for listSystemCredentials
     *
     * .
     *
     */
    public function testListSystemCredentials()
    {
    }

    /**
     * Test case for listSystemRoles
     *
     * .
     *
     */
    public function testListSystemRoles()
    {
    }

    /**
     * Test case for listSystems
     *
     * .
     *
     */
    public function testListSystems()
    {
    }

    /**
     * Test case for updateSystem
     *
     * .
     *
     */
    public function testUpdateSystem()
    {
    }

    /**
     * Test case for updateSystemCredential
     *
     * .
     *
     */
    public function testUpdateSystemCredential()
    {
    }

    /**
     * Test case for updateSystemCredentialOfType
     *
     * .
     *
     */
    public function testUpdateSystemCredentialOfType()
    {
    }

    /**
     * Test case for updateSystemRole
     *
     * .
     *
     */
    public function testUpdateSystemRole()
    {
    }
}
