<?php
/**
 * TagApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Agave\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Agave Platform Science API
 *
 * Power your digital lab and reduce the time from theory to discovery using the Agave Science-as-a-Service API Platform. Agave provides hosted services that allow researchers to manage data, conduct experiments, and publish and share results from anywhere at any time.
 *
 * OpenAPI spec version: 2.2.14
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: unset
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Agave\Client;

use \Agave\Client\Configuration;
use \Agave\Client\ApiException;
use \Agave\Client\ObjectSerializer;

/**
 * TagApiTest Class Doc Comment
 *
 * @category Class
 * @package  Agave\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class TagApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for addTag
     *
     * Creat a new tag.
     *
     */
    public function testAddTag()
    {
    }

    /**
     * Test case for addTagResource
     *
     * Add resources to tag.
     *
     */
    public function testAddTagResource()
    {
    }

    /**
     * Test case for clearTagPermissions
     *
     * Clear tag permissions.
     *
     */
    public function testClearTagPermissions()
    {
    }

    /**
     * Test case for clearTagResources
     *
     * Clear all tagged resources.
     *
     */
    public function testClearTagResources()
    {
    }

    /**
     * Test case for deleteTag
     *
     * Delete tag.
     *
     */
    public function testDeleteTag()
    {
    }

    /**
     * Test case for deleteTagPermissionForUser
     *
     * Remove user tag permission.
     *
     */
    public function testDeleteTagPermissionForUser()
    {
    }

    /**
     * Test case for getTagDetails
     *
     * Tag Details.
     *
     */
    public function testGetTagDetails()
    {
    }

    /**
     * Test case for getTagPermissionForUser
     *
     * List tag permissions for a user.
     *
     */
    public function testGetTagPermissionForUser()
    {
    }

    /**
     * Test case for getTaggedResource
     *
     * Get tagged item details.
     *
     */
    public function testGetTaggedResource()
    {
    }

    /**
     * Test case for listTagHistory
     *
     * Tag history.
     *
     */
    public function testListTagHistory()
    {
    }

    /**
     * Test case for listTagPermissions
     *
     * List permissionss set for a given tag id.
     *
     */
    public function testListTagPermissions()
    {
    }

    /**
     * Test case for listTagResources
     *
     * Tagged items.
     *
     */
    public function testListTagResources()
    {
    }

    /**
     * Test case for listTags
     *
     * Available tags.
     *
     */
    public function testListTags()
    {
    }

    /**
     * Test case for removeTagResource
     *
     * Remove resource from tag.
     *
     */
    public function testRemoveTagResource()
    {
    }

    /**
     * Test case for updateTag
     *
     * Update tag.
     *
     */
    public function testUpdateTag()
    {
    }

    /**
     * Test case for updateTagPermission
     *
     * Grant permission.
     *
     */
    public function testUpdateTagPermission()
    {
    }

    /**
     * Test case for updateTagPermissionForUser
     *
     * Update user permission on tag.
     *
     */
    public function testUpdateTagPermissionForUser()
    {
    }

    /**
     * Test case for updateTagResource
     *
     * Add resource to tag.
     *
     */
    public function testUpdateTagResource()
    {
    }
}
